### ISSUE TITLE
Update to latest kotlinx serialization

### ISSUE THREAD

**Issue by asarazan** [asarazan/martok#10]

**Comment by asarazan** [comment]
@vaudevillen - when you have a moment can you link me to the changes that need making here?

**Comment by vaudevillen** [comment]
are you talking about how the changes from pre 1.0? That quicktype was behind on?

**Comment by asarazan** [comment]
ohai! Yeah I basically just vaguely knew that qt was behind on something or other-- but from what I can tell the code we're generating is actually correct for the latest version?

**Comment by vaudevillen** [comment]
yeah, if you're using `PrimitiveSerialDescriptor`, looks like it's already updated
