### ISSUE TITLE
generated kotlin sealed classes from typescript unions allow multiple types for a property when only one is valid

### ISSUE THREAD

**Issue by vaudevillen** [asarazan/martok#39]
If a sealed class is generated from type unions, sometimes the property can only have one valid type (like a specific case in an enum), but that's not reflected in the generated class.

For example, this typescript file for type `SketchyUpdate` will generate the kotlin sealed class `SketchyUpdate` with an inner type `SketchyUpdateLifecycleEvent`:
<img height="300" src="https://user-images.githubusercontent.com/12077504/170328531-11b522c7-487c-4956-8ad0-12b5cf885a1b.png"/>

<img height="300" src="https://user-images.githubusercontent.com/12077504/170328764-e78afcb3-e907-4b43-9da3-6fca9ce7906c.png"/>

`SketchyUpdateLifecycleEvent.actionType` can only be `ActionType.LIFECYCLE_EVENT`, but that's not reflected in the generated class, and it is possible to initialize the class with the wrong `ActionType`.

**Comment by asarazan** [comment]
Resolved in https://github.com/asarazan/martok/pull/40
